function dynamicsJacobian = dynamics_jacobian_collocInertial(h1,in2,in3,in4,in5,in6,in7,in8,in9,in10)
%DYNAMICS_JACOBIAN_COLLOCINERTIAL
%    DYNAMICSJACOBIAN = DYNAMICS_JACOBIAN_COLLOCINERTIAL(H1,IN2,IN3,IN4,IN5,IN6,IN7,IN8,IN9,IN10)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    25-Jul-2016 03:44:42

l1 = in6(1,:);
l2 = in6(2,:);
l3 = in6(3,:);
l4 = in6(4,:);
m1 = in6(9,:);
m2 = in6(10,:);
m3 = in6(11,:);
m4 = in6(12,:);
u01 = in4(1,:);
u02 = in4(2,:);
u03 = in4(3,:);
u04 = in4(4,:);
u11 = in5(1,:);
u12 = in5(2,:);
u13 = in5(3,:);
u14 = in5(4,:);
x01 = in2(1,:);
x02 = in2(2,:);
x03 = in2(3,:);
x04 = in2(4,:);
x05 = in2(5,:);
x06 = in2(6,:);
x07 = in2(7,:);
x08 = in2(8,:);
x11 = in3(1,:);
x12 = in3(2,:);
x13 = in3(3,:);
x14 = in3(4,:);
x15 = in3(5,:);
x16 = in3(6,:);
x17 = in3(7,:);
x18 = in3(8,:);
xd01 = in7(1,:);
xd02 = in7(2,:);
xd03 = in7(3,:);
xd04 = in7(4,:);
xd05 = in7(5,:);
xd06 = in7(6,:);
xd07 = in7(7,:);
xd08 = in7(8,:);
xd11 = in8(1,:);
xd12 = in8(2,:);
xd13 = in8(3,:);
xd14 = in8(4,:);
xd15 = in8(5,:);
xd16 = in8(6,:);
xd17 = in8(7,:);
xd18 = in8(8,:);
