function dynamicsEquation = dynamics_functionQuadcopter(h1,in2,u01,len1)
%DYNAMICS_FUNCTIONQUADCOPTER
%    DYNAMICSEQUATION = DYNAMICS_FUNCTIONQUADCOPTER(H1,IN2,U01,LEN1)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    16-Aug-2016 10:39:47

x04 = in2(4,:);
x05 = in2(5,:);
x06 = in2(6,:);
x07 = in2(7,:);
x08 = in2(8,:);
x09 = in2(9,:);
x010 = in2(10,:);
x011 = in2(11,:);
x012 = in2(12,:);
dynamicsEquation = [x07;x08;x09;x010;x011;x012;u01.*sin(x04).*sin(x06)+u01.*cos(x04).*cos(x06).*sin(x05)-len1.*x010.^2.*sin(x04).*sin(x06).*(1.0./2.0)-len1.*x012.^2.*sin(x04).*sin(x06).*(1.0./2.0)-len1.*x010.^2.*cos(x04).*cos(x06).*sin(x05).*(1.0./2.0)-len1.*x011.^2.*cos(x04).*cos(x06).*sin(x05).*(1.0./2.0)-len1.*x012.^2.*cos(x04).*cos(x06).*sin(x05).*(1.0./2.0)+len1.*x010.*x012.*cos(x04).*cos(x06)-len1.*x010.*x011.*cos(x05).*cos(x06).*sin(x04).*(1.0./2.0)-len1.*x011.*x012.*cos(x04).*cos(x05).*sin(x06).*(1.0./2.0)+len1.*x010.*x012.*sin(x04).*sin(x05).*sin(x06)-len1.*x010.*x012.*cos(x04).*cos(x05).^2.*cos(x06).*(1.0./2.0);-u01.*cos(x06).*sin(x04)+len1.*x010.^2.*cos(x06).*sin(x04).*(1.0./2.0)+len1.*x012.^2.*cos(x06).*sin(x04).*(1.0./2.0)+u01.*cos(x04).*sin(x05).*sin(x06)-len1.*x010.^2.*cos(x04).*sin(x05).*sin(x06).*(1.0./2.0)-len1.*x011.^2.*cos(x04).*sin(x05).*sin(x06).*(1.0./2.0)-len1.*x012.^2.*cos(x04).*sin(x05).*sin(x06).*(1.0./2.0)+len1.*x010.*x012.*cos(x04).*sin(x06)+len1.*x011.*x012.*cos(x04).*cos(x05).*cos(x06).*(1.0./2.0)-len1.*x010.*x011.*cos(x05).*sin(x04).*sin(x06).*(1.0./2.0)-len1.*x010.*x012.*cos(x06).*sin(x04).*sin(x05)-len1.*x010.*x012.*cos(x04).*cos(x05).^2.*sin(x06).*(1.0./2.0);u01.*cos(x04).*cos(x05)-len1.*x010.^2.*cos(x04).*cos(x05).*(1.0./2.0)-len1.*x011.^2.*cos(x04).*cos(x05).*(1.0./2.0)-len1.*x011.*x012.*sin(x04).*(1.0./2.0)+len1.*x010.*x011.*sin(x04).*sin(x05).*(1.0./2.0)+len1.*x010.*x012.*cos(x04).*cos(x05).*sin(x05).*(1.0./2.0)-9.81e2./1.0e2;(x011.*x012+x010.*x011.*sin(x05)+u01.*cos(x04).*sin(x05).*2.45e-2)./cos(x05);u01.*sin(x04).*(-2.45e-2)-x010.*x012.*cos(x05);(x010.*x011+u01.*cos(x04).*2.45e-2+x011.*x012.*sin(x05))./cos(x05)];
