function dynamicsJacobian = dynamics_jacobian(h1,in2,in3,in4)
%DYNAMICS_JACOBIAN
%    DYNAMICSJACOBIAN = DYNAMICS_JACOBIAN(H1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    30-Dec-2015 17:53:48

l1 = in4(1,:);
l2 = in4(2,:);
l3 = in4(3,:);
u1 = in3(1,:);
u2 = in3(2,:);
u3 = in3(3,:);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
x5 = in2(5,:);
x6 = in2(6,:);
