function dynamicsEquation = dynamics_functionQuadrotorParams(h1,in2,in3,in4)
%DYNAMICS_FUNCTIONQUADROTORPARAMS
%    DYNAMICSEQUATION = DYNAMICS_FUNCTIONQUADROTORPARAMS(H1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    17-Aug-2016 01:10:38

mass = in4(2,:);
radius = in4(1,:);
u01 = in3(1,:);
u02 = in3(2,:);
u03 = in3(3,:);
u04 = in3(4,:);
x04 = in2(4,:);
x05 = in2(5,:);
x06 = in2(6,:);
x07 = in2(7,:);
x08 = in2(8,:);
x09 = in2(9,:);
x010 = in2(10,:);
x011 = in2(11,:);
x012 = in2(12,:);
dynamicsEquation = [x07;x08;x09;x010;x011;x012;((sin(x04).*sin(x06)+cos(x04).*cos(x06).*sin(x05)).*(u01+u02+u03+u04))./mass;-((cos(x06).*sin(x04)-cos(x04).*sin(x05).*sin(x06)).*(u01+u02+u03+u04))./mass;(mass.*(-9.81e2./1.0e2)+u01.*cos(x04).*cos(x05)+u02.*cos(x04).*cos(x05)+u03.*cos(x04).*cos(x05)+u04.*cos(x04).*cos(x05))./mass;(x011.*x012.*(4.0e1./2.3e1)+radius.*u02.*cos(x05).*2.534782608695652e2-radius.*u04.*cos(x05).*2.534782608695652e2+x010.*x011.*sin(x05).*(6.0./2.3e1)-x011.*x012.*cos(x04).^2.*(1.7e1./2.3e1)+u01.*cos(x04).*sin(x05).*(4.9e1./8.0)-u02.*cos(x04).*sin(x05).*(4.9e1./8.0)+u03.*cos(x04).*sin(x05).*(4.9e1./8.0)-u04.*cos(x04).*sin(x05).*(4.9e1./8.0)-radius.*u01.*sin(x04).*sin(x05).*2.534782608695652e2+radius.*u03.*sin(x04).*sin(x05).*2.534782608695652e2+x010.*x011.*cos(x04).^2.*sin(x05).*(1.7e1./2.3e1)-x011.*x012.*cos(x04).^2.*cos(x05).^2.*(1.7e1./2.3e1)+x011.^2.*cos(x04).*cos(x05).*sin(x04).*(1.7e1./2.3e1)-x012.^2.*cos(x04).*cos(x05).*sin(x04).*(1.7e1./2.3e1)+x010.*x012.*cos(x04).*cos(x05).*sin(x04).*sin(x05).*(1.7e1./2.3e1))./cos(x05);u01.*sin(x04).*(-4.9e1./8.0)+u02.*sin(x04).*(4.9e1./8.0)-u03.*sin(x04).*(4.9e1./8.0)+u04.*sin(x04).*(4.9e1./8.0)-radius.*u01.*cos(x04).*2.534782608695652e2+radius.*u03.*cos(x04).*2.534782608695652e2-x010.*x012.*cos(x05)-x010.*x011.*sin(x04.*2.0).*(1.7e1./4.6e1)-x012.^2.*cos(x04).^2.*cos(x05).*sin(x05).*(1.7e1./2.3e1)+x010.*x012.*cos(x04).^2.*cos(x05).*(1.7e1./2.3e1)+x011.*x012.*cos(x04).*sin(x04).*sin(x05).*(1.7e1./2.3e1);(x010.*x011.*(6.0./2.3e1)+u01.*cos(x04).*(4.9e1./8.0)-u02.*cos(x04).*(4.9e1./8.0)+u03.*cos(x04).*(4.9e1./8.0)-u04.*cos(x04).*(4.9e1./8.0)-radius.*u01.*sin(x04).*2.534782608695652e2+radius.*u03.*sin(x04).*2.534782608695652e2+x011.*x012.*sin(x05).*(4.0e1./2.3e1)+x010.*x011.*cos(x04).^2.*(1.7e1./2.3e1)-x011.*x012.*cos(x04).^2.*sin(x05).*(1.7e1./2.3e1)-x012.^2.*cos(x04).*cos(x05).*sin(x04).*sin(x05).*(1.7e1./2.3e1)+x010.*x012.*cos(x04).*cos(x05).*sin(x04).*(1.7e1./2.3e1))./cos(x05)];
